<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>boo</string>
	</array>
	<key>name</key>
	<string>Boo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(#|//)</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.source.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|from|if|else|elif|unless|for|in|while|continue|break|pass|return|override|namespace|enum|try|raise|except|ensure|assert|yield|callable|goto|virtual|get|set|of|ref|unsafe|new|match|case|otherwise|debug|using|lock|block|macro|self|event)\b</string>
			<key>name</key>
			<string>keyword.control.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(isa|is|as|cast)\b</string>
			<key>name</key>
			<string>keyword.operator.types.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*=|/=|%=|\+=|-=|\*\*=|&gt;&gt;=|&lt;&lt;=|&amp;=|\|=|\^=|\+\+|--)</string>
			<key>name</key>
			<string>keyword.operator.assignment.augmented.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*|/|%|\+|-|\*\*|&gt;&gt;|&lt;&lt;|&amp;|\||\^)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;|&gt;|&lt;=|&gt;=|==|!=)</string>
			<key>name</key>
			<string>keyword.operator.comparison.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\)|\[|\]|{|}|:)</string>
			<key>name</key>
			<string>keyword.operator.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?(f|F|L)?\b</string>
			<key>name</key>
			<string>constant.numeric.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|value)\b</string>
			<key>name</key>
			<string>constant.language.source.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.source.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.source.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.double.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sbyte|short|int|long|byte|ushort|uint|ulong|single|double|decimal|char|string|bool|object|duck|date)\b</string>
			<key>name</key>
			<string>storage.type.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(public|protected|internal|private|abstract|final|static|partial)\b</string>
			<key>name</key>
			<string>storage.modifier.source.boo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(print|enumerate|gets|prompt|join|map|array|matrix|iterator|shellp|shell|shellm|super|enemurate|range|reversed|zip|cat|typeof|sizeof|len)\b</string>
			<key>name</key>
			<string>support.function.source.boo</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.source.boo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-z_]+[A-Za-z_0-9]*\s+(as))\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\[)\s*(Getter|Setter|Property)\s*(?=\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.property.source.boo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))\s*(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.property.source.boo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\()</string>
					<key>contentName</key>
					<string>meta.name.property.source.boo</string>
					<key>end</key>
					<string>(?=,|\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?=[A-Za-z_][A-Za-z0-9_]*)</string>
							<key>contentName</key>
							<string>entity.name.function.source.boo</string>
							<key>end</key>
							<string>(?![A-Za-z0-9_])</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(def)\s+(?=[A-Za-z_][A-Za-z0-9_]*\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.source.boo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))\s*(?:(\:?))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.source.boo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[A-Za-z_][A-Za-z0-9_]*)</string>
					<key>contentName</key>
					<string>entity.name.function.source.boo</string>
					<key>end</key>
					<string>(?![A-Za-z0-9_])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#entity_name_function</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.boo</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.function.parameters.source.boo</string>
					<key>end</key>
					<string>(?=\)\s*\:?)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#keyword_arguments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(def|constructor|destructor)\b</string>
			<key>name</key>
			<string>keyword.control.source.boo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(def|do)(?=\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.closure.source.boo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))\s*(?:(\:?))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.source.boo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.boo</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.function.parameters.source.boo</string>
					<key>end</key>
					<string>(?=\)\s*\:?)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#keyword_arguments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(class|interface|struct)\s+(?=[a-zA-Z_][a-zA-Z_0-9]*\s*\:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.source.boo</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.class.source.boo</string>
			<key>end</key>
			<string>\s*(:)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.old-style.source.boo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity_name_class</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(class|interface|struct)\s+(?=[a-zA-Z_][a-zA-Z_0-9]*\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.source.boo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))\s*(?:(\:)|(.*$\n?))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.boo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.missing-section-begin.source.boo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.source.boo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[A-Za-z_][A-Za-z0-9_]*)</string>
					<key>contentName</key>
					<string>entity.name.class.source.boo</string>
					<key>end</key>
					<string>(?![A-Za-z0-9_])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#entity_name_class</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.boo</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.class.inheritance.source.boo</string>
					<key>end</key>
					<string>(?=\)|:)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;=\(|,)\s*</string>
							<key>contentName</key>
							<string>entity.other.inherited-class.source.boo</string>
							<key>end</key>
							<string>\s*(?:(,)|(?=\)))</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.inheritance.source.boo</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>keyword_arguments</key>
		<dict>
			<key>begin</key>
			<string>\b([a-zA-Z_][a-zA-Z_0-9]*)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(?:(,)|(?=\n|\)[:\s]))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.parameters.python</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.boo</string>
	<key>uuid</key>
	<string>40d7173c-d213-4009-938e-5249ec75849d</string>
</dict>
</plist>
